### ISSUE TITLE
Possible dumbfuck on my end.

### ISSUE THREAD

**Issue by dfault-user** [pxlsspace/Pxls#169]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.
        at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:863)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:68)
        at space.pxls.data.Database.<init>(Database.java:43)
        at space.pxls.App.main(App.java:81)
```

Possible fucky wucky on my end, but Pxls throws up after this point in execution:
```
Warning: Cannot find board.dat in working directory, using blank board
Warning: Cannot find heatmap.dat in working directory, using blank heatmap
Warning: Cannot find placemap.dat in working directory, using blank placemap
Warning: Cannot find virginmap.dat in working directory, using blank virginmap
```

**Comment by FlyingSixtySix** [comment]
I've experienced the SLF4J exception, but I haven't looked into it yet.

The second set of warnings occur when the listed files aren't found in configured storage directory. The `board.dat`, `heatmap.dat`, and `virginmap.dat` files are automatically generated.

**Comment by TechAdvancedCyborg** [comment]
The issue is due a misconfigured config file...
