### ISSUE TITLE
Request did not contain an Upgrade header, upgrade is not permitted

### ISSUE THREAD

**Issue by Kaydax** [pxlsspace/Pxls#208]
Running the server and I configured everything correctly (I hope) but I keep getting this error spammed once anyone loads onto the site.

Site is being proxied through nginx and ran through cloudflare using https and certs from certbot

If you need anything else just ask

Error:
```
02:16:21.178 [XNIO-1 I/O-4] ERROR io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ GET /ws}
java.lang.IllegalStateException: UT000133: Request did not contain an Upgrade header, upgrade is not permitted
        at io.undertow.server.HttpServerExchange.upgradeChannel(HttpServerExchange.java:894) ~[pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.websockets.WebSocketProtocolHandshakeHandler.handleRequest(WebSocketProtocolHandshakeHandler.java:193) ~[pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91) ~[pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.handlers.form.EagerFormParsingHandler.handleRequest(EagerFormParsingHandler.java:73) ~[pxls-1.0-SNAPSHOT.jar:?]
        at space.pxls.util.AuthReader.handleRequest(AuthReader.java:54) ~[pxls-1.0-SNAPSHOT.jar:?]
        at space.pxls.util.IPReader.handleRequest(IPReader.java:36) ~[pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) [pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [pxls-1.0-SNAPSHOT.jar:?]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582) [pxls-1.0-SNAPSHOT.jar:?]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:466) [pxls-1.0-SNAPSHOT.jar:?]

```

**Comment by FlyingSixtySix** [comment]
It's been a couple of months; I'm closing the issue. Reply if this is still occurring!

**Comment by puyoxyz** [comment]
You need this in your nginx config:

```
location /ws {
    proxy_connect_timeout 7d;
    proxy_send_timeout 7d;
    proxy_read_timeout 7d;
    proxy_pass http://localhost:4567/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

Maybe this should be documented somewhere?

([source](https://discord.com/channels/298948748317294592/455255880888483840/655551541499134001))

**Comment by spark1313** [comment]
That would belong in the Wiki (https://github.com/pxlsspace/Pxls/wiki)
IF WE HAD ONE!.....Dinkleberg...
[https://c.tenor.com/N2hV1al2rjcAAAAM/if-i-had-one-angry.gif](url)
